import type { App } from './types/app'

export const apps: App[] = [
  {
    id: 'pilgrimage',
    title: 'Pilgrimage',
    description: '지도 위에서 현재 위치를 검색하고 GPS로 바로 이동하는 순례 길잡이 앱.',
    href: '/pilgrimage/',
    status: 'live',
    tags: ['React', '지도', 'GPS'],
    color: '#0a84ff',
    icon: '🗺️',
  },
  {
    id: 'feelmyrythm',
    title: 'FeelMyRythm',
    description: '앙상블 연습을 위한 동기화 메트로놈과 악보·연습 관리 앱.',
    href: '/feelmyrythm/',
    status: 'live',
    tags: ['React', 'FastAPI', 'Web Audio'],
    color: '#b78a2d',
    icon: '🎵',
  },
  {
    id: 'multtara',
    title: 'Multtara',
    description: '새로운 구현을 준비하고 있는 포트폴리오 프로젝트.',
    href: '/multtara/',
    status: 'wip',
    tags: ['Coming soon'],
    color: '#7c6cf2',
    icon: '✨',
  },
  {
    id: 'garak',
    title: 'Garak',
    description: '솔로부터 오케스트라까지 브라우저에서 작성·재생·내보내는 웹 악보 편집기.',
    href: '/garak/',
    status: 'beta',
    tags: ['React', 'VexFlow', 'MusicXML'],
    color: '#b76f46',
    icon: '🎼',
  },
  {
    id: 'vue',
    title: 'Vue',
    description: 'Vue와 OpenLayers로 지도와 도형 편집을 체험하는 공간정보 데모.',
    href: '/vue/',
    status: 'live',
    tags: ['Vue', 'OpenLayers', 'Demo'],
    color: '#42b883',
    icon: '🌍',
  },
  {
    id: 'dukkeobi',
    title: 'Dukkeobi',
    description: '주거·안전 지도 프로젝트를 데이터 변경 없이 둘러보는 읽기 전용 아카이브.',
    href: '/dukkeobi/',
    status: 'live',
    tags: ['Spring MVC', 'Map', 'Read-only'],
    color: '#4d8b55',
    icon: '🏠',
  },
  {
    id: 'ddit-finalproject',
    title: 'DDIT FinalProject',
    description: '레거시 팀 프로젝트의 구성과 구현 내용을 소개하는 읽기 전용 아카이브.',
    href: '/ddit-finalproject/',
    status: 'live',
    tags: ['Spring MVC', 'Java', 'Archive'],
    color: '#e15d44',
    icon: '🧩',
  },
  {
    id: 'react',
    title: 'React',
    description: 'React와 TypeScript로 구현한 프런트엔드 포트폴리오 프로젝트.',
    href: '/react/',
    status: 'live',
    tags: ['React', 'TypeScript', 'Vite'],
    color: '#149eca',
    icon: '⚛️',
  },
  {
    id: 'wgang',
    title: 'Wgang',
    description: '별도 서비스로 운영 중인 Wgang 웹 애플리케이션.',
    href: 'https://wgang.art/',
    external: true,
    status: 'live',
    tags: ['External service'],
    color: '#111111',
    icon: '↗️',
  },
]
