import type { App } from './types/app'

export const apps: App[] = [
  {
    id: 'pilgrimage',
    title: 'Pilgrimage',
    description: '지도 위에서 현재 위치를 검색하고 GPS로 바로 이동하는 순례 길잡이 앱.',
    href: '/pilgrimage/',
    status: 'live',
    tags: ['React', '지도', 'GPS'],
    color: '#0a84ff',
    icon: '🗺️',
  },
  {
    id: 'feelmyrythm',
    title: 'FeelMyRythm',
    description: '앙상블 연습을 위한 동기화 메트로놈과 악보·연습 관리 앱.',
    href: '/feelmyrythm/',
    status: 'live',
    tags: ['React', 'FastAPI', 'Web Audio'],
    color: '#b78a2d',
    icon: '🎵',
  },
  {
    id: 'multtara',
    title: 'Multtara',
    description: '새로운 구현을 준비하고 있는 포트폴리오 프로젝트.',
    href: '/multtara/',
    status: 'wip',
    tags: ['Coming soon'],
    color: '#7c6cf2',
    icon: '✨',
  },
  {
    id: 'vueproject',
    title: 'VueProject',
    description: 'Vue와 OpenLayers·GeoServer를 활용한 공간정보 웹 프로젝트.',
    href: '/vueproject/',
    status: 'wip',
    tags: ['Vue', 'OpenLayers', 'GeoServer'],
    color: '#42b883',
    icon: '🌍',
  },
  {
    id: 'dukkeobi',
    title: 'Dukkeobi',
    description: '주거 정보와 안전 현황을 지도에서 확인하는 Spring MVC 프로젝트.',
    href: '/dukkeobi/',
    status: 'wip',
    tags: ['Spring MVC', 'MyBatis', 'PostgreSQL'],
    color: '#4d8b55',
    icon: '🏠',
  },
  {
    id: 'finalproject',
    title: 'FinalProject',
    description: 'Spring MVC 기반으로 구현한 팀 포트폴리오 프로젝트.',
    href: '/finalproject/',
    status: 'wip',
    tags: ['Spring MVC', 'Java', 'WebSocket'],
    color: '#e15d44',
    icon: '🧩',
  },
  {
    id: 'react',
    title: 'React',
    description: 'React와 TypeScript로 구현한 프런트엔드 포트폴리오 프로젝트.',
    href: '/react/',
    status: 'live',
    tags: ['React', 'TypeScript', 'Vite'],
    color: '#149eca',
    icon: '⚛️',
  },
  {
    id: 'wgang',
    title: 'Wgang',
    description: '별도 서비스로 운영 중인 Wgang 웹 애플리케이션.',
    href: 'https://wgang.art/',
    external: true,
    status: 'live',
    tags: ['External service'],
    color: '#111111',
    icon: '↗️',
  },
]
